export enum OptimisticTxType {
  // Post-related actions
  CREATE_POST = "CREATE_POST",
  CREATE_COMMENT = "CREATE_COMMENT",
  CREATE_QUOTE = "CREATE_QUOTE",
  CREATE_REPOST = "CREATE_REPOST",
  CREATE_COLLECT = "CREATE_COLLECT",

  // Account-related actions
  FOLLOW_ACCOUNT = "FOLLOW_ACCOUNT",
  UNFOLLOW_ACCOUNT = "UNFOLLOW_ACCOUNT",
  BLOCK_ACCOUNT = "BLOCK_ACCOUNT",
  UNBLOCK_ACCOUNT = "UNBLOCK_ACCOUNT",
  ASSIGN_USERNAME = "ASSIGN_USERNAME",
  UNASSIGN_USERNAME = "UNASSIGN_USERNAME",
  SET_ACCOUNT_METADATA = "SET_ACCOUNT_METADATA",
  ADD_ACCOUNT_MANAGER = "ADD_ACCOUNT_MANAGER",
  REMOVE_ACCOUNT_MANAGER = "REMOVE_ACCOUNT_MANAGER",

  // Group-related actions
  CREATE_GROUP = "CREATE_GROUP",
  JOIN_GROUP = "JOIN_GROUP",
  LEAVE_GROUP = "LEAVE_GROUP",
  FOLLOW_GROUP = "FOLLOW_GROUP",
  UNFOLLOW_GROUP = "UNFOLLOW_GROUP",
  BAN_GROUP_ACCOUNT = "BAN_GROUP_ACCOUNT",
  UNBAN_GROUP_ACCOUNT = "UNBAN_GROUP_ACCOUNT"
}
