#!/bin/sh

# Inject environment variables into the Next.js runtime config
cat <<EOF > /app/.env
NEXT_PUBLIC_IS_PRODUCTION=${NEXT_PUBLIC_IS_PRODUCTION}
NEXT_PUBLIC_LENS_NETWORK=${NEXT_PUBLIC_LENS_NETWORK}
NEXT_PUBLIC_OG_URL=${NEXT_PUBLIC_OG_URL}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
NEXT_PUBLIC_THIRDWEB_TOKEN=${NEXT_PUBLIC_THIRDWEB_TOKEN}
NEXT_PUBLIC_DECENT_API_KEY=${NEXT_PUBLIC_DECENT_API_KEY}
NEXT_PUBLIC_OPENSEA_API_KEY=${NEXT_PUBLIC_OPENSEA_API_KEY}
NEXT_PUBLIC_RARIBLE_API_KEY=${NEXT_PUBLIC_RARIBLE_API_KEY}
EOF

# Execute the CMD
exec "$@"
