#!/bin/bash

#/ Usage: script/release/testnet
#/ Relase to testnet

set -e

git config user.name lenster-bot
git config user.email github-bot@lenster.xyz

git checkout testnet

git merge --no-edit --no-ff main
git push origin testnet

git checkout main
git rebase testnet
git push origin main
