#!/bin/bash

#/ Usage: script/bootstrap
#/ Install dependencies and make sure everything is ready to go.

echo "Setting up env vars 🌎"
echo "Updating apps/web env vars 🌎"
cd apps/web; cp .env.example .env
cd ../../
echo "Updating apps/prerender env vars 🌎"
cd apps/prerender; cp .env.example .env
cd ../../
echo "Updating packages/workers/curated-profiles env vars 🌎"
cd packages/workers/curated-profiles; cp .dev.vars.example .dev.vars
cd ../../../
echo "Updating packages/workers/freshdesk env vars 🌎"
cd packages/workers/freshdesk; cp .dev.vars.example .dev.vars
cd ../../../
echo "Updating packages/workers/metadata env vars 🌎"
cd packages/workers/metadata
# Generate private key and insert into .dev.vars
random_hex=$(head -c 32 /dev/urandom | xxd -p -c 32)
echo "RANDOM_HEX=$random_hex" > .dev.vars
cd ../../../
echo "Updating packages/workers/sts-generator env vars 🌎"
cd packages/workers/sts-generator; cp .dev.vars.example .dev.vars
cd ../../../
# -------------------------------------
echo "Installing dependencies 📦"
yarn install
echo "Dependencies installed 📦"
# -------------------------------------
echo "Project bootstrap complete 🎉"
