#!/bin/bash

#/ Usage: script/bootstrap
#/ Install dependencies and make sure everything is ready to go.

echo "Setting up env vars 🌎"
echo "Updating apps/web env vars 🌎"
cd apps/web; cp .env.example .env
cd ../../
echo "Updating apps/prerender env vars 🌎"
cd apps/prerender; cp .env.example .env
cd ../../
echo "Updating packages/workers/freshdesk env vars 🌎"
cd packages/workers/freshdesk; cp .dev.vars.example .dev.vars
cd ../../../
echo "Updating packages/workers/metadata env vars 🌎"
cd packages/workers/metadata
# Generate private key and insert into .dev.vars
random_hex=$(head -c 32 /dev/urandom | xxd -p -c 32)
echo "BUNDLR_PRIVATE_KEY=$random_hex" > .dev.vars
cd ../../../
echo "Updating packages/workers/sts-generator env vars 🌎"
cd packages/workers/sts-generator; cp .dev.vars.example .dev.vars
cd ../../../
# -------------------------------------
echo "Installing dependencies 📦"
pnpm install --frozen-lockfile
echo "Dependencies installed 📦"
echo "Installing playwright 🎭"
npx playwright install
echo "Playwright installed 🎭"
echo "GraphQL Codegen 🧬"
pnpm run codegen
echo "GraphQL Codegen complete 🧬"
# -------------------------------------
echo "Project bootstrap complete 🎉"
