#!/bin/bash

#/ Usage: script/clean-branches
#/ Delete all branches except main and testnet.

echo "Deleting all branches except 'main', 'testnet' and 'staging' 🗑"
git branch | grep -v "main" | grep -v "testnet" | grep -v "staging" | xargs git branch -D
echo "Branches deleted 🎉"
