#!/bin/bash

#/ Usage: script/clean-branches
#/ Delete all branches except main and testnet.

echo "Deleting all branches except 'main', 'testnet', 'staging', 'sandbox' and 'staging-sandbox' 🗑"
git branch | grep -v "main" | grep -v "testnet" | grep -v "staging" | grep -v "sandbox" | grep -v "staging-sandbox" | xargs git branch -D
echo "Branches deleted 🎉"
