#!/bin/bash

#/ Usage: script/clean
#/ Clean all node_modules and bun.lockb files recursively.

echo "Deleting all node_modules and bun.lockb files recursively 🗑"
find . -name "node_modules" -type d -prune -exec rm -rf '{}' + -print
find . -name "bun.lockb" -type f -prune -exec rm -rf '{}' + -print
echo "node_modules and bun.lockb files deleted 🎉"
