#!/bin/bash

#/ Usage: script/bootstrap
#/ Install dependencies and make sure everything is ready to go.

set -e

git config user.name lenster-bot
git config user.email github-bot@lenster.xyz

git checkout testenv

git merge --no-edit --no-ff main
git push origin testenv

git checkout main
git rebase testenv
git push origin main
