#!/bin/bash

#/ Usage: script/release
#/ Release to all environments.

git config user.name admin
git config user.email admin@bcharity.net

branches=("testnet" "staging")

for branch in "${branches[@]}"
do
    echo "Releasing to $branch"
    git pull origin main >> /dev/null
    git checkout $branch
    git merge main
    git push origin $branch
    git checkout main
done

echo "Done"
