#!/bin/bash

#/ Usage: script/release.sh <branch>
#/ Release to specified branch

set -e

branch=$1

git config user.name lenster-bot
git config user.email github-bot@lenster.xyz

git checkout $branch

git merge --no-edit --no-ff main
git push origin $branch

git checkout main
git rebase $branch
git push origin main
