#!/bin/bash

#/ Usage: script/sync-branches
#/ Sync testnet and sandbox branch with main branch.

echo "Sync testnet branch with main branch 🔄"
git pull origin main
git checkout testnet
git merge main
git push origin testnet
git checkout main
git checkout sandbox
git merge main
git push origin sandbox
git checkout main
echo "Branches synced 🎉"
