#!/bin/bash

# Usage: script/update-dependencies
# Update dependencies across all packages

branch_name="update-dependencies-$(date +%Y-%m-%d-%H-%M)"
commit_message="Update dependencies across all packages 📦"

# Check for uncommitted changes
if [[ $(git status --porcelain) ]]; then
  echo "Uncommitted changes detected. Please commit or stash them before running this script."
  exit 1
fi

# Create a new branch
git checkout -b "$branch_name"

# Update dependencies
pnpm update --interactive --recursive --latest

# Check for changes
if [[ ! $(git status --porcelain) ]]; then
  echo "No changes in dependencies. Exiting."
  exit 0
fi

# Call the clean script
./script/clean

# Install dependencies again
pnpm install

# Commit changes
git add .
git commit -m "$commit_message"

# Push the branch
git push -u origin "$branch_name"

echo "Dependencies updated and pushed to branch $branch_name."
