#!/bin/bash

#/ Usage: script/update-lock-file
#/ Create a branch to update a lock file.

# Delete update-lock-file branch if it exists
if git branch | grep -q "update-lock-file"; then
  echo "Deleting update-lock-file branch 🗑"
  git branch -D update-lock-file
  echo "Branch deleted 🎉"
fi

# Create update-lock-file branch
echo "Creating update-lock-file branch 🌱"
git checkout -b update-lock-file
echo "Branch created 🎉"

# Update lock file
echo "Updating lock file 📦"
script/clean && pnpm install
# Git operations
git add -A
git commit -am "chore: update lock file 📦"
git push origin update-lock-file
gh pr create --fill
echo "Lock file updated 🎉"
