#!/bin/bash

#/ Usage: script/update-lock-file
#/ Create a branch to update a lock file with a unique name.

# Generate a unique branch name using a timestamp
branch_name="update-lock-file-$(date +%Y%m%d%H%M%S)"

# Create a new update-lock-file branch with the timestamp
echo "Creating $branch_name branch 🌱"
git checkout -b "$branch_name"
echo "Branch $branch_name created 🎉"

# Update lock file
echo "Updating lock file 📦"
script/clean && pnpm install
# Git operations
git add -A
git commit -am "chore: update lock file 📦"
git push origin "$branch_name"
gh pr create --fill
echo "Lock file updated and PR created for $branch_name 🎉"
