#!/bin/bash

#/ Usage: script/clean-branches
#/ Delete all branches except main and testnet.

echo "Deleting all branches except 'main' and 'testnet' 🗑"
git branch | grep -v "main" | grep -v "testnet" | xargs git branch -D
echo "Branches deleted 🎉"
