import { PROFILE, PUBLICATION } from "@hey/data/tracking";

const filteredEvents = [
  PROFILE.FOLLOW,
  PROFILE.SUPER_FOLLOW,
  PUBLICATION.LIKE,
  PUBLICATION.NEW_POST,
  PUBLICATION.NEW_COMMENT,
  PUBLICATION.MIRROR,
  PUBLICATION.COLLECT_MODULE.COLLECT,
  PUBLICATION.WIDGET.POLL.VOTE
];

export default filteredEvents;
